# fly.toml app configuration file generated for movie-recommender-fragrant-shape-7289 on 2025-05-27T13:38:07-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'movie-recommender-fragrant-shape-7289'
primary_region = 'den'

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1


  
